const USDT_DECIMALS = 1_000_000n;

export const DEFAULT_BUNDLE_COVERAGE_THRESHOLD = 0.8;
export const DEFAULT_MAX_BUNDLE_FUNDERS = 3;
export const DEFAULT_CROSS_CHAIN_BRIDGE_AMOUNT_THRESHOLD_RAW = (100_000n * USDT_DECIMALS).toString();
export const DEFAULT_CROSS_CHAIN_BRIDGE_EPISODE_SHARE_THRESHOLD = 0.25;
export const DEFAULT_DRAIN_EPISODE_WINDOW_MS = 24 * 60 * 60 * 1000;
