// Generated by scripts/generateUnifiedGoldenBindings.ts. Do not edit.
export const LOCKED_GOLDEN_MANIFEST_SHA256 = "4d1f2568d3676cf1ee2e4411bc70e056d1f6fc80997b2919e3da4705811cb407";

export const SELECTED_ATTRIBUTION_POLICY = {
  version: "selected-attribution-policy-v1",
  policy: "proportional",
  lockedGoldenManifestSha256: LOCKED_GOLDEN_MANIFEST_SHA256
} as const;
