// Generated by scripts/generateUnifiedGoldenBindings.ts. Do not edit.
export const LOCKED_GOLDEN_MANIFEST_SHA256 = "4d1f2568d3676cf1ee2e4411bc70e056d1f6fc80997b2919e3da4705811cb407";

export const SCORING_POLICY_V4 = {
  version: "scoring-signal-matrix-v4",
  lockedGoldenManifestSha256: LOCKED_GOLDEN_MANIFEST_SHA256,
  rules: [
    {
      "ruleId": "clean_confirmed_context",
      "adjudicatedSourceCaseId": "synthetic-one-legitimate-transfer",
      "exactScore": 0,
      "expectedDecision": "ACCEPTABLE"
    },
    {
      "ruleId": "collector_transit",
      "adjudicatedSourceCaseId": "regression-tbl7",
      "exactScore": 45,
      "expectedDecision": "REVIEW"
    },
    {
      "ruleId": "correlated_dense_transit",
      "adjudicatedSourceCaseId": "synthetic-dense-wallet",
      "exactScore": 45,
      "expectedDecision": "REVIEW"
    },
    {
      "ruleId": "dangerous_approval_no_debit",
      "adjudicatedSourceCaseId": "synthetic-dangerous-approval-no-debit",
      "exactScore": 55,
      "expectedDecision": "REVIEW"
    },
    {
      "ruleId": "direct_blacklist_at_event",
      "adjudicatedSourceCaseId": "synthetic-direct-blacklist-1pct",
      "exactScore": 90,
      "expectedDecision": "DECLINE"
    },
    {
      "ruleId": "fan_out",
      "adjudicatedSourceCaseId": "blind-wallet-scope",
      "exactScore": 40,
      "expectedDecision": "REVIEW"
    },
    {
      "ruleId": "high_volume_transit",
      "adjudicatedSourceCaseId": "blind-incoming-deposit-scope",
      "exactScore": 45,
      "expectedDecision": "REVIEW"
    },
    {
      "ruleId": "indirect_restriction_context",
      "adjudicatedSourceCaseId": "regression-tbl7",
      "exactScore": 45,
      "expectedDecision": "REVIEW"
    },
    {
      "ruleId": "neutral_no_observed_risk",
      "adjudicatedSourceCaseId": "synthetic-empty-wallet",
      "exactScore": 0,
      "expectedDecision": "ACCEPTABLE"
    },
    {
      "ruleId": "no_usdt_activity",
      "adjudicatedSourceCaseId": "synthetic-new-no-usdt",
      "exactScore": 0,
      "expectedDecision": "ACCEPTABLE"
    },
    {
      "ruleId": "operational_wallet",
      "adjudicatedSourceCaseId": "synthetic-operational-wallet",
      "exactScore": 5,
      "expectedDecision": "ACCEPTABLE"
    },
    {
      "ruleId": "rapid_forwarding",
      "adjudicatedSourceCaseId": "blind-history-scope",
      "exactScore": 35,
      "expectedDecision": "REVIEW"
    },
    {
      "ruleId": "route_transit",
      "adjudicatedSourceCaseId": "blind-route-scope",
      "exactScore": 42,
      "expectedDecision": "REVIEW"
    },
    {
      "ruleId": "selected_amount_transit",
      "adjudicatedSourceCaseId": "blind-selected-amount-scope",
      "exactScore": 40,
      "expectedDecision": "REVIEW"
    },
    {
      "ruleId": "unknown_without_risk_pattern",
      "adjudicatedSourceCaseId": "synthetic-unknown-no-pattern",
      "exactScore": 0,
      "expectedDecision": "ACCEPTABLE"
    },
    {
      "ruleId": "victim_confirmed_debit",
      "adjudicatedSourceCaseId": "synthetic-victim-debit",
      "exactScore": 50,
      "expectedDecision": "REVIEW"
    }
  ]
} as const;

export const GOLDEN_CASE_EXPECTATIONS_V4 = [
  {
    "rowId": "blind-history-scope",
    "exactScore": 35,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron:0dc7e3e0970c5656ab022e9ed40a4513406d802d1addf8ed0fea6ef98185c992:28400449:trc20_transfer:TWkvffFDMsqbmTLkMHMABmw452Hyq98cdn:TEognYE7Sy6jiKxkDt2EbFgkUYUfsp9U2j",
        "lane": "neutral",
        "role": "recipient",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:e72cc41539d419cae96e5a686e86a72389efd2bb62a96436db7cf8f6de1ed6de:27535111:trc20_transfer:TEognYE7Sy6jiKxkDt2EbFgkUYUfsp9U2j:TJZxcWCDxf5zgYMA1snogPWxyR9MeXDwoq",
        "lane": "pattern",
        "role": "transit_sender",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "invariant:duplicate_raw_rows_do_not_compound_risk",
      "relation:rapid_inbound_then_outbound=>pattern_review",
      "unknown_counterparty_identity_does_not_create_risk"
    ]
  },
  {
    "rowId": "blind-incoming-deposit-scope",
    "exactScore": 45,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron:63474c89b94ca7aab79d13fdbec63d201e5205741be36b33dab94e9120e5749c:140021301:trc20_transfer:TSv32fr41xwv3dh99PmtdxkhWguMEEuoVh:TEQFTqaZndCrkPKByU7ge1jajht1N7ZQye",
        "lane": "pattern",
        "role": "high_volume_transit_wallet",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:c06914f4ee1c634000c091a2599467283a78986fd133766d831986963c49adb7:110039861:trc20_transfer:TPQdKv8LyQmwt7RvP6zUt2oLdTpAH2JF8q:TSv32fr41xwv3dh99PmtdxkhWguMEEuoVh",
        "lane": "pattern",
        "role": "high_volume_recipient",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:d07c9beda59f421792aff262c85df898a90b5deadd5dd513a5aa18d803732968:176054048:trc20_transfer:TSv32fr41xwv3dh99PmtdxkhWguMEEuoVh:TGQ7Vb86HGYVY6gGRjzV8jX3EYBykC1uHx",
        "lane": "pattern",
        "role": "high_volume_sender",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "created_by_contract_metadata_does_not_establish_badness",
      "dense_high_throughput_activity_requires_review_but_is_not_hard_proof",
      "invariant:contract_creation_metadata_alone_does_not_raise_risk",
      "relation:high_volume_fan_in_and_fan_out=>pattern_review"
    ]
  },
  {
    "rowId": "blind-route-scope",
    "exactScore": 42,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron:5fa69283ed50ed992fd7c52781b447f6ffb91dacbe59d173aee1ca7a890c287e:60205832:trc20_transfer:TRddZMs7MJmbpQFuBpFxK4BDt5tA4LLPDu:TSS4AWbbkhxys3sdgafKnSwazya1Bz42TB",
        "lane": "pattern",
        "role": "transit_sender",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:6572f00b8fe01349113b73ad8ce525104fe3c0ab8ca7b198542fd1da653df0d6:130171439:trc20_transfer:TRddZMs7MJmbpQFuBpFxK4BDt5tA4LLPDu:TBL8TQTyw2GjwV3g9eZM27ajgywKZzaz3n",
        "lane": "pattern",
        "role": "route_sender",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:e61963e6f43de4bb9f51665ae89b9b857da8d8ac236570b52ec16d1cacc6c914:218269331:trc20_transfer:TSuX19hxKRXMSjJXYjYzXFMaQownWhrs15:TRddZMs7MJmbpQFuBpFxK4BDt5tA4LLPDu",
        "lane": "pattern",
        "role": "route_recipient",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "created_by_contract_is_not_a_service_boundary_or_badness_proof",
      "invariant:later_contract_metadata_does_not_create_hard_evidence",
      "material_transit_pattern_is_bounded_review_context",
      "relation:near_total_fan_in_to_fan_out=>pattern_review"
    ]
  },
  {
    "rowId": "blind-selected-amount-scope",
    "exactScore": 40,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron:a43430e8a3bebaed4193d1e1696f8b4f36be0fddcf26acfdaa948afb6e482161:73431297:trc20_transfer:TV6bBsrCXz2sDSBMZhvc7vHqDwjc65ALZX:TSS4AWbbkhxys3sdgafKnSwazya1Bz42TB",
        "lane": "pattern",
        "role": "selected_amount_sender",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:c1a11536b22e85f390c4110ea709f3d5fae9d76b2a6ba7684c51887c19b73dea:2334590:trc20_transfer:TANPg1qXHmuc53VW4BrcJJM338X5oVs1m9:TV6bBsrCXz2sDSBMZhvc7vHqDwjc65ALZX",
        "lane": "pattern",
        "role": "selected_amount_recipient",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "invariant:unknown_counterparty_identity_alone_does_not_raise_risk",
      "relation:selected_inflow_then_near_total_outflow=>pattern_review",
      "selected_amount_transit_pattern_requires_review_without_creating_hard_proof",
      "unknown_counterparty_identity_does_not_create_risk"
    ]
  },
  {
    "rowId": "blind-wallet-scope",
    "exactScore": 40,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron:0ce8094ac171b8f6ecd1b4d75e656a07447b628a1327368eea0e3f2e3f2051a7:118220500:trc20_transfer:THEPxoMWVkaywy7ZH7zYG7pYNXDwr7RZVx:TYXN5ZiJLuzUyAY2dxdzdNjbwnUkSGB1it",
        "lane": "pattern",
        "role": "fan_out_funder_recipient",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:5fe9f5e086208277160c3cca16e4be0dd1dc91cd7644818ec46bb07eec136f85:186058296:trc20_transfer:TYXN5ZiJLuzUyAY2dxdzdNjbwnUkSGB1it:TAFdghHDf13ckUNZRw6dit4C4KfzRFWY1k",
        "lane": "pattern",
        "role": "fan_out_sender",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:ce3faf4c510c706087fe42a63b1acf47fcf32347141701539e35060bf4881185:99868063:trc20_transfer:TYXN5ZiJLuzUyAY2dxdzdNjbwnUkSGB1it:TVp15u1ypYgBMnrxEB2euXqfoMyT1gy3Xu",
        "lane": "pattern",
        "role": "fan_out_sender",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "fan_out_pattern_requires_review_but_is_not_hard_proof",
      "invariant:no_hard_evidence=>no_decline",
      "relation:concentrated_inflow_to_broad_fan_out=>pattern_review",
      "unknown_counterparty_identity_does_not_create_risk"
    ]
  },
  {
    "rowId": "regression-tbl7",
    "exactScore": 45,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron-label:TFTWNgDBkQ5wQoP8RXpRznnHvAVV8x5jLu:HTX 4:2026-06-24T19:07:31.675Z",
        "lane": "context",
        "role": "recipient",
        "directness": "direct",
        "timing": "later"
      },
      {
        "canonicalFactId": "tron:a1d51f3d44dd8915289c9d1445f6d0b3637e4ea9499fa53a43cf2e12b1fe427b:266855246:trc20_transfer:TBL7SHuSwpXnK6fWfwuRWrbpBjSqCQscQy:TUpHuDkiCCmwaTZBHZvQdwWzGNm5t8J2b9",
        "lane": "pattern",
        "role": "collector_sender",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:abcaaa26eac3aa337b657822a8508a7c62e1c07714896769508bb43d313b968f:144631851:trc20_transfer:TVLbdSKuuYaduZts5WtEqaPhzZbyAvjben:TBL7SHuSwpXnK6fWfwuRWrbpBjSqCQscQy",
        "lane": "pattern",
        "role": "collector_recipient",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:aebefabc597cd289a0a51ef57323d1cc7631a158ba9d4eee44532475c668627c:260857380:trc20_transfer:TBL7SHuSwpXnK6fWfwuRWrbpBjSqCQscQy:TUpHuDkiCCmwaTZBHZvQdwWzGNm5t8J2b9",
        "lane": "pattern",
        "role": "transit_sender",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "collector_pattern_requires_review_but_is_not_hard_proof",
      "invariant:service_metadata_without_sanctions_evidence=>no_decline",
      "later_service_metadata_does_not_reclassify_prior_events",
      "relation:historical_htx_exposure=>compliance_review"
    ]
  },
  {
    "rowId": "regression-tqr",
    "exactScore": 45,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron-label:TFTWNgDBkQ5wQoP8RXpRznnHvAVV8x5jLu:HTX 4:2026-06-24T19:07:31.675Z",
        "lane": "context",
        "role": "recipient",
        "directness": "direct",
        "timing": "later"
      },
      {
        "canonicalFactId": "tron:21d1e8877533b6ca18262873925e5bb17e278271f0618788d544a45af97b9c4f:213878824:trc20_transfer:TU4vEruvZwLLkSfV9bNw12EJTPvNr7Pvaa:TQrNKbdG7LwwQ2FqD6iHgvsNJeaVKD7NzP",
        "lane": "pattern",
        "role": "high_volume_recipient",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:4bc3bdcbfffed63a4052e8f0df3c48a80e898d27d055e6cf5f0382127cea3f6d:9757374:trc20_transfer:TQrNKbdG7LwwQ2FqD6iHgvsNJeaVKD7NzP:TV1Fgburk14GtGqVYwRvY9DUZrr5NZBV32",
        "lane": "pattern",
        "role": "transit_sender",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:53893c1d280dc8946507714973a5a3d951940ee58a7f35725ab78aa780b527ec:261543361:trc20_transfer:TQrNKbdG7LwwQ2FqD6iHgvsNJeaVKD7NzP:TS14bcf8i78WiwhupfeVLHzTNo7fpgg2vt",
        "lane": "pattern",
        "role": "high_volume_sender",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "high_throughput_hub_activity_requires_review_but_is_not_hard_proof",
      "invariant:service_metadata_without_hard_authority=>no_decline",
      "later_service_metadata_does_not_reclassify_prior_events",
      "relation:historical_htx_plus_sustained_transit=>compliance_review"
    ]
  },
  {
    "rowId": "synthetic-500-pages",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron-state:direct_history_page:T9yD14Nj9j7xAB4dbGeiX9h8unkKi6mJHp:1:2026-07-23T00:00:11.000Z",
        "lane": "neutral",
        "role": "history_subject",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "coverage_depth_does_not_create_positive_risk",
      "empty_attribution_is_policy_invariant",
      "invariant:coverage_depth_alone_does_not_raise_risk"
    ]
  },
  {
    "rowId": "synthetic-ambiguous-delivery",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron-state:automatic_retry_forbidden:T9yD14Nj9j7xAB4dbGeiX9h8unkKLxmGkn::2026-07-23T00:00:16.000Z",
        "lane": "neutral",
        "role": "delivery_subject",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron-state:delivery_unknown:T9yD14Nj9j7xAB4dbGeiX9h8unkKLxmGkn::2026-07-23T00:00:16.000Z",
        "lane": "neutral",
        "role": "delivery_subject",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "automatic_retry_policy_does_not_change_risk",
      "delivery_uncertainty_does_not_imply_subject_risk",
      "invariant:delivery_uncertainty_alone_does_not_raise_risk"
    ]
  },
  {
    "rowId": "synthetic-bybit-plus-hard-evidence",
    "exactScore": 90,
    "expectedDecision": "DECLINE",
    "facts": [
      {
        "canonicalFactId": "tron-label:T9yD14Nj9j7xAB4dbGeiX9h8unkKv2TRTS:Bybit:",
        "lane": "neutral",
        "role": "cex_subject",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron-label:T9yD14Nj9j7xAB4dbGeiX9h8unkL2ynyg7:Frozen at event:2026-07-23T00:00:05.000Z",
        "lane": "hard",
        "role": "recipient",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:0000000000000000000000000000000000000000000000000000000000000006:0:trc20_transfer:T9yD14Nj9j7xAB4dbGeiX9h8unkKv2TRTS:T9yD14Nj9j7xAB4dbGeiX9h8unkKv2TRTS",
        "lane": "neutral",
        "role": "cex_self_transfer",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:0000000000000000000000000000000000000000000000000000000000000006:1:trc20_transfer:T9yD14Nj9j7xAB4dbGeiX9h8unkL2ynyg7:T9yD14Nj9j7xAB4dbGeiX9h8unkKv2TRTS",
        "lane": "hard",
        "role": "recipient",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "direct_at_event_hard_evidence_is_not_diluted_by_safe_context",
      "invariant:neutral_service_transfer_does_not_cancel_hard_evidence",
      "relation:direct_at_event_blacklist_evidence=>decline",
      "subject_role_and_event_timing_bind_the_hard_fact"
    ]
  },
  {
    "rowId": "synthetic-dangerous-approval-no-debit",
    "exactScore": 55,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron-state:dangerous_unlimited_approval:T9yD14Nj9j7xAB4dbGeiX9h8unkL2ynyg7:T9yD14Nj9j7xAB4dbGeiX9h8unkL2ynyg7:2026-07-23T00:00:06.000Z",
        "lane": "pattern",
        "role": "approval_owner",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "approval_without_confirmed_debit_is_not_exact_drain_proof",
      "dangerous_approval_context_requires_review",
      "invariant:no_confirmed_debit=>no_decline",
      "relation:dangerous_approval_without_debit=>review"
    ]
  },
  {
    "rowId": "synthetic-dense-wallet",
    "exactScore": 45,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron-state:dense_fan_in_fan_out:T9yD14Nj9j7xAB4dbGeiX9h8unkKawPyGg:64:2026-07-23T00:00:10.000Z",
        "lane": "pattern",
        "role": "fan_in_fan_out_subject",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "dense_fan_in_fan_out_pattern_requires_review_but_is_not_hard_proof",
      "invariant:density_without_hard_evidence=>no_decline",
      "relation:dense_fan_in_fan_out=>pattern_review",
      "unknown_counterparty_identity_does_not_create_risk"
    ]
  },
  {
    "rowId": "synthetic-direct-blacklist-1pct",
    "exactScore": 90,
    "expectedDecision": "DECLINE",
    "facts": [
      {
        "canonicalFactId": "tron-label:T9yD14Nj9j7xAB4dbGeiX9h8unkL2ynyg7:Frozen at event:2026-07-23T00:00:04.000Z",
        "lane": "hard",
        "role": "recipient",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:0000000000000000000000000000000000000000000000000000000000000005:1:trc20_transfer:T9yD14Nj9j7xAB4dbGeiX9h8unkL2ynyg7:T9yD14Nj9j7xAB4dbGeiX9h8unkKsN8FyA",
        "lane": "hard",
        "role": "recipient",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "direct_at_event_hard_evidence_is_not_diluted_by_unlabeled_funds",
      "invariant:unlabeled_transfer_volume_does_not_cancel_hard_evidence",
      "relation:direct_at_event_blacklist_evidence=>decline",
      "subject_role_and_event_timing_bind_the_hard_fact"
    ]
  },
  {
    "rowId": "synthetic-duplicates",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron-state:duplicate_evidence:T9yD14Nj9j7xAB4dbGeiX9h8unkKsN8FyA::2026-07-23T00:00:12.000Z",
        "lane": "neutral",
        "role": "branch_subject",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "duplicate_canonical_facts_count_once",
      "invariant:duplicate_identical_facts_do_not_compound_risk"
    ]
  },
  {
    "rowId": "synthetic-dust-spam",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron-state:dust_spam:T9yD14Nj9j7xAB4dbGeiX9h8unkKT76qbH::2026-07-23T00:00:09.000Z",
        "lane": "neutral",
        "role": "dust_recipient",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "invariant:unsolicited_dust_received_by_subject_does_not_raise_subject_risk",
      "unsolicited_dust_to_a_recipient_does_not_raise_subject_risk"
    ]
  },
  {
    "rowId": "synthetic-empty-wallet",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [],
    "scoreProperties": [
      "an_empty_evidence_set_has_no_positive_risk_relation",
      "empty_attribution_is_policy_invariant",
      "invariant:no_adverse_evidence=>no_risk_increase"
    ]
  },
  {
    "rowId": "synthetic-key-exhaustion",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron-state:provider_key_exhausted:T9yD14Nj9j7xAB4dbGeiX9h8unkL9GFcbh:key-1:2026-07-23T00:00:15.000Z",
        "lane": "neutral",
        "role": "coverage_subject",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "empty_attribution_is_policy_invariant",
      "invariant:provider_failure_alone_does_not_raise_subject_risk",
      "provider_key_exhaustion_does_not_create_positive_risk"
    ]
  },
  {
    "rowId": "synthetic-new-no-usdt",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron-state:wallet_created:T9yD14Nj9j7xAB4dbGeiX9h8unkKT76qbH:2026-07-23T00:00:01.000Z:2026-07-23T00:00:01.000Z",
        "lane": "neutral",
        "role": "new_wallet_subject",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "empty_attribution_is_policy_invariant",
      "invariant:wallet_newness_alone_does_not_raise_risk",
      "wallet_newness_without_usdt_activity_does_not_create_risk"
    ]
  },
  {
    "rowId": "synthetic-one-legitimate-transfer",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron-label:T9yD14Nj9j7xAB4dbGeiX9h8unkKv2TRTS:Bybit:",
        "lane": "neutral",
        "role": "recipient",
        "directness": "direct",
        "timing": "at_event"
      },
      {
        "canonicalFactId": "tron:0000000000000000000000000000000000000000000000000000000000000003:0:trc20_transfer:T9yD14Nj9j7xAB4dbGeiX9h8unkKv2TRTS:T9yD14Nj9j7xAB4dbGeiX9h8unkKawPyGg",
        "lane": "neutral",
        "role": "recipient",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "known_cex_source_is_a_terminal_boundary_not_bad_provenance",
      "relation:direct_legitimate_cex_transfer=>neutral_context"
    ]
  },
  {
    "rowId": "synthetic-operational-wallet",
    "exactScore": 5,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron-state:old_active_operational_wallet:T9yD14Nj9j7xAB4dbGeiX9h8unkKLxmGkn::2026-07-23T00:00:08.000Z",
        "lane": "neutral",
        "role": "operational_wallet",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "invariant:operational_wallet_status_and_unknown_sender_alone_do_not_raise_risk",
      "operational_age_and_activity_do_not_create_positive_risk",
      "unknown_counterparty_identity_does_not_create_risk"
    ]
  },
  {
    "rowId": "synthetic-reorder",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron:000000000000000000000000000000000000000000000000000000000000000e:0:trc20_transfer:T9yD14Nj9j7xAB4dbGeiX9h8unkKv2TRTS:T9yD14Nj9j7xAB4dbGeiX9h8unkKv2TRTS",
        "lane": "neutral",
        "role": "self_sender_recipient",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "event_order_does_not_change_equivalent_self_transfer_evidence",
      "invariant:event_reordering_preserves_decision",
      "invariant:self_transfer_order_does_not_create_risk"
    ]
  },
  {
    "rowId": "synthetic-restart",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron-state:immutable_attempt_replay:T9yD14Nj9j7xAB4dbGeiX9h8unkL2ynyg7:same-input:2026-07-23T00:00:14.000Z",
        "lane": "neutral",
        "role": "attempt_subject",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "duplicate_canonical_facts_count_once",
      "immutable_attempt_replay_does_not_duplicate_risk",
      "invariant:replayed_fact_does_not_compound_risk",
      "invariant:same_input_replay_preserves_decision"
    ]
  },
  {
    "rowId": "synthetic-unknown-no-pattern",
    "exactScore": 0,
    "expectedDecision": "ACCEPTABLE",
    "facts": [
      {
        "canonicalFactId": "tron:0000000000000000000000000000000000000000000000000000000000000004:0:trc20_transfer:T9yD14Nj9j7xAB4dbGeiX9h8unkKv2TRTS:T9yD14Nj9j7xAB4dbGeiX9h8unkKi6mJHp",
        "lane": "neutral",
        "role": "recipient",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "attribution_policies_preserve_the_same_event_allocations",
      "invariant:unknown_counterparty_identity_alone_does_not_raise_risk",
      "unknown_counterparty_identity_without_a_pattern_does_not_create_risk"
    ]
  },
  {
    "rowId": "synthetic-victim-debit",
    "exactScore": 50,
    "expectedDecision": "REVIEW",
    "facts": [
      {
        "canonicalFactId": "tron-state:confirmed_victim_debit:T9yD14Nj9j7xAB4dbGeiX9h8unkL9GFcbh:T9yD14Nj9j7xAB4dbGeiX9h8unkL2ynyg7:2026-07-23T00:00:07.000Z",
        "lane": "hard",
        "role": "victim",
        "directness": "direct",
        "timing": "at_event"
      }
    ],
    "scoreProperties": [
      "hard_victimization_evidence_requires_protective_review",
      "invariant:victim_role_does_not_transfer_counterparty_risk_to_subject",
      "outbound_debit_is_not_balance_origin_attribution",
      "victim_role_prevents_perpetrator_attribution"
    ]
  }
] as const;
